### ISSUE TITLE
Need for a new MNO wrapper (v7) for adding an optional memo

### ISSUE THREAD

**Issue by 314159265359879** [syvita/nothing#4]
Are you guys reading the updated discussion here?
Looks like we may need a Nothing v7 after all… if we want sip010’s to have a memo field, their may be an updated sip010 trait. Since the current deployment is not yet activated it can still be changed, if they do we will need to make a new (v7) MNO wrapper.

https://github.com/stacksgov/sips/pull/5#issuecomment-838825652

**Comment by cryptopanter** [comment]
If the upgrade is deployed, then doesn't the memo add up automatically?

**Comment by asteriabtc** [comment]
> If the upgrade is deployed, then doesn't the memo add up automatically?

What do you mean the memo 'add[s] up automatically'?

**Comment by 314159265359879** [comment]
> 
> 
> If the upgrade is deployed, then doesn't the memo add up automatically?

No the standard doesn't work that way. It is more of a guideline for any other contract for an FT. The trait just tells you what minimum requirements there are. Such as a transfer function, a metadata file and in this case a transfer-memo. 

The addition of a transfer memo means you have to make a new contract. I do think the memo is important and that is shared in the thread I linked above. I think hstove is just very busy and hasn't gotten around to updating the standard trait and uploading it. Not a big deal for Nothing but also a blocker for CC. Hopefully soon. Lets just wait for it before we update Nothing to _lucky_ v7.

**Comment by asteriabtc** [comment]
**UPDATE:** SIP-010 has been updated to include an optional memo. We'll need a v7 wrapper for MNO in the Big Upgrade. This is now a High Priority task.

**Comment by 314159265359879** [comment]
I will sort this out with Hozz, so you guys can focus on CC.

**Comment by asteriabtc** [comment]
`get-balance-of` has also been changed to `get-balance`

**Comment by 314159265359879** [comment]
> 
> 
> `get-balance-of` has also been changed to `get-balance`

Hozz just finished making the [v7](https://explorer.stacks.co/txid/0xcccefbdb941211702f0601e5ca2f91e72367771850e12149c64ce4b49fc34ab2?chain=mainnet) contract when Friedger re-requested that change. I am afraid Hozz is not willing to go through more changes on this at the moment he is to tied up in other work. 

I have made a copy of his contract from the explorer and made some changes to it:
Hozz v7 with changes to line 6 (updated link to standard trait), line 43 (WMNO not WMNO7), line 48 (get-balance)

@friedger and @asteriabtc would you have a look at the wrapped-nothing-7 I made in the contracts folder?

Also I think we need changes to lines 14 and 25 where it says .micro-nthng if we deploy this on an other principle than where that contract resides? The full address is: SP32AEEF6WW5Y0NMJ1S8SBSZDAY8R5J32NBZFPKKZ.micro-nthng

The way I see it maybe we can deploy this to Asteria's public address here https://explorer.stacks.co/address/SP343J7DNE122AVCSC4HEK4MF871PW470ZSXJ5K66?chain=mainnet

After that Friedger could wrap some of his MNO (and/or Asteria can unwrap/rewrap whats on that ...K66 address) and send it to the faucet address or use a new faucet address for now?

The way I see it even though v7 was already deployed this should still be called Wrapped Nothing 7 (as that previous one will go unused) we get rid of the "v" in the name because it sounds better and makes for better stories. This is Wrapped Nothing (Lucky Number) 7. Should be the last iteration for the foreseeable future ;-)

**Comment by friedger** [comment]
The history should be updated.

@314159265359879  The contracts sit in `packages/contracts`

**Comment by friedger** [comment]
Ideally we have a clarinet setup in that package

**Comment by friedger** [comment]
The contract calls should be `(contract-call? SP32AEEF6WW5Y0NMJ1S8SBSZDAY8R5J32NBZFPKKZ.micro-nthng transfer...) `

**Comment by 314159265359879** [comment]
> 
> 
> The history should be updated.

Indeed, and I will make it so as soon as this last contract is deployed to SIP 010 spec. 

> 
> @314159265359879 The contracts sit in `packages/contracts`

Thanks, I moved it there now. 

> 
> 
> Ideally we have a clarinet setup in that package

For all other projects ofc, not for Nothing ;-)

> 
> 
> The contract calls should be `(contract-call? SP32AEEF6WW5Y0NMJ1S8SBSZDAY8R5J32NBZFPKKZ.micro-nthng transfer...) `

Alright, thanks changed it.

**Comment by 314159265359879** [comment]
@asteriabtc 
Before you redeploy would you mind checking this comment, Is Michael right about this. I figure it could be because Hozz would have deployed this to the address where the micro.nthng contract resides, should we change this?

![image](https://user-images.githubusercontent.com/33360391/120988626-0692f380-c77f-11eb-996d-d7986a3a2a20.png)

**Comment by 314159265359879** [comment]
Hozz deployed v8 yesterday, only caught his tweet about it just now, thanks Hozz!:
https://explorer.stacks.co/txid/SP32AEEF6WW5Y0NMJ1S8SBSZDAY8R5J32NBZFPKKZ.wrapped-nothing-v8?chain=mainnet

Hozz [deployed v7](https://explorer.stacks.co/txid/0xcccefbdb941211702f0601e5ca2f91e72367771850e12149c64ce4b49fc34ab2?chain=mainnet) in between the approx. 2 hours we thought we had a new SIP-010 standard and the idea to change `get-balance-of` to `get-balance` so that last change is covered with v8. Nothing v7 will go down in history as the lucky contract that never got used. I am sure we'll keep on wrapping. In the future we'll offer unwrapping options on nothingtoken.com so you can go back to MNO and to the latest wrapper (v8).

v8 supports memo's when transferring and that is ofc essential. You can say "Thanks for Nothing" or "Nothing else matters", "You are Nothing and I love you", etc etc. 

And hence this change. Nothing is likely still the first taker of the happy SIP-010 standard. One down, two to go for activation.
