### ISSUE TITLE
Deploy send-many sip10 contract

### ISSUE THREAD

**Issue by friedger** [syvita/nothing#6]
There should be a send-many contract that allows to transfer sip-10 tokens similar to https://explorer.stacks.co/txid/SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.send-many-memo?chain=mainnet and https://explorer.stacks.co/txid/SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.send-many?chain=mainnet

The contract can be used for nothing.

**Comment by asteriabtc** [comment]
I think we've already done this. Send many is [included in wrapped-nothing-v6](https://explorer.syvita.org/txid/SP32AEEF6WW5Y0NMJ1S8SBSZDAY8R5J32NBZFPKKZ.wrapped-nothing-v6?chain=mainnet).
